Repository broma-arma/BromA-Framework-A3-Addon, pull requests merged in 2019-04, with the labels that each got.

#147 Update chedaki.sqf
  loadouts/factions/chedaki.sqf
Labels: Priority: Low, Status: Revision Needed, Type: Enhancement

#143 remove RH _M16A2 + _M16A2GL Replace with GST M16A2
  loadouts/content/broma-weapon-list.sqf
Labels: Priority: Low, Status: Accepted, Type: Enhancement

#146 Loadout updates
  loadouts/content/broma-weapon-list.sqf
  loadouts/faction-list.sqf
  loadouts/factions/frdesert.sqf
  loadouts/factions/frwinter.sqf
  loadouts/factions/frwood.sqf
  loadouts/factions/german.sqf
Labels: Priority: Medium, Status: Accepted, Type: Bug, Type: Enhancement
